name: nasqar_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base==4.2.2 
  - r-shiny
  - bioconductor-clusterprofiler
  - r-dt
  - r-shinydashboard
  - r-shinyjs
  - r-shinyBS
  - r-shinycssloaders
  - r-uuid
  - bioconductor-pathview
  - r-plotly
  - r-markdown 
  - r-devtools  
  - r-shinycssloaders
  - r-devtools
  - r-biocmanager
  - r-ggupset
  - r-ggridges
  - r-europepmc
  - r-rhandsontable
  - r-readr
  - r-rcolorbrewer
  - r-heatmaply
  - r-ggthemes
  - r-igraph
  - r-sodium
  - r-nmf
  - r-rclipboard
  - r-vennDiagram
  - bioconductor-enhancedvolcano
  - bioconductor-sva
  - bioconductor-deseq2
  - r-pheatmap
  - r-gplots
  - r-ggvis
  - umap-learn  
  - ucsc-cell-browser
  - bioconductor-multtest
  - libsodium
  - bioconductor-complexheatmap
  - bioconductor-interactivecomplexheatmap
  - bioconductor-debrowser
  - bioconductor-rsamtools

