apiVersion: v1
kind: Service
metadata:
  name: {{ include "nasqar.fullname" . }}
  labels:
    {{- include "nasqar.labels" . | nindent 4 }}
spec:
  sessionAffinity: ClientIP
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nasqar.selectorLabels" . | nindent 4 }}
