{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nasqar.serviceAccountName" . }}
  labels:
{{ include "nasqar.labels" . | nindent 4 }}
{{- end -}}
